### ISSUE TITLE
Run properly

### ISSUE THREAD

**Issue by Esther561** [Team-5-Cyan-Camel/Flatmates#81]
Hi guys，

This project cannot run properly on my laptop, even if I configure the .env file as required.  
![1622885030(1)](https://user-images.githubusercontent.com/72179615/120886931-794b8400-c644-11eb-9816-9d278524cdea.png)
 
Thanks

**Comment by dikunong** [comment]
Authentication failed - are you sure your Atlas username and password are correct? Are they meant to be the same?  
I just got it up and running using their provided backend proxy (see step 4 in Set Up in their README), so I might suggest using that for testing :)

**Comment by JChamberlain28** [comment]
I am going to close this issue as it seems to be an issue with misconfiguration, not the codebase or instructions. @Esther561 feel free to re-open the issue if you are still unable to set up atlas correctly when following the instructions so that we can investigate. I think there may be an issue with the username and password you have provided. I have not been able to replicate this.
